import './globals.css'
import { Inter as FontSans } from 'next/font/google'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { ThemeProvider } from '@/components/theme-provider'
import { cn } from '@/lib/utils'
import { SiteHeader } from '@/components/site-header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
})

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' suppressHydrationWarning>
      <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
        <body
          className={cn(
            'min-h-screen bg-white font-sans text-slate-900 antialiased dark:bg-gradient-to-b from-[#191919] to-[#15162c] dark:text-slate-50 flex flex-col items-center',
            fontSans.variable
          )}
        >
          <main className='min-h-screen flex flex-col items-center'>
            <SiteHeader />
            {children}
          </main>
          <TailwindIndicator />
        </body>
      </ThemeProvider>
    </html>
  )
}
